pipeline {
	agent {
		label 'agent-step5'
	}

	stages {
		stage('Build image') {
			steps {
				sh '''
					Dockerfile -t 192.168.56.112:5002/step5-docker:${BUILD_NUMBER} . 
				'''
			}
		}

		stage('Push image') {
			steps {
				sh '''
					docker push 192.168.56.112:5002/step5-docker:${BUILD_NUMBER}
				'''
			}
		}

	}
}
