---
rocky_container_name: rocky-ssh
ubuntu_container_name: ubuntu-ssh

rocky_podman_host_port: 2223
rocky_docker_host_port: 2224
ubuntu_podman_host_port: 2225
ubuntu_docker_host_port: 2226

container_network_name: container_network

registry_host: localhost
registry_port_podman: 5001
registry_port_docker: 5002
image_tag: latest
