---
- name: Update DNF package cache
  become: true
  ansible.builtin.dnf:
    update_cache: true

- name: Install required packages
  become: true
  ansible.builtin.dnf:
    name:
      - dnf-plugins-core
      - python3-requests
    state: present

- name: Add Docker
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker.ce.repo
    owner: root
    group: root
    mode: '0644'

- name: Install Docker packages
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Configure insecure Registry
  become: true
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: Restart Docker

- name: Start Docker service
  become: true
  ansible.builtin.service:
    name: docker
    state: started

- name: Check Docker service status
  ansible.builtin.service_facts:

- name: Add vagrant user to docker group
  ansible.builtin.user:
    name: vagrant
    groups: docker
    append: true

- name: Continue if Docker is running
  ansible.builtin.debug:
    msg: "Docker is running"
  when: ansible_facts.services['docker.service'].state == 'running'


- name: Fail if Docker is not running
  ansible.builtin.fail:
    msg: "Docker is not running"
  when: ansible_facts.services['docker.service'].state != 'running'

- name: Restart Docker if it is not running
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted
  when: ansible_facts.services['docker.service'].state == 'running'
