---
- name: Create build directory
  ansible.builtin.file:
    path: /tmp/step3
    state: directory
    mode: '0755'

- name: Copy Rocky Containerfile
  ansible.builtin.copy:
    src: roles/step3/files/Containerfile-rocky
    dest: /tmp/step3/Containerfile-rocky

- name: Copy Ubuntu Containerfile
  ansible.builtin.copy:
    src: roles/step3/files/Containerfile-ubuntu
    dest: /tmp/step3/Containerfile-ubuntu

- name: Copy SSH public key
  ansible.builtin.copy:
    remote_src: true
    src: /home/vagrant/.ssh/id-genericuser.pub
    dest: /tmp/step3/id-key-genericuser.pub