---
- name: Allow SSH Rocky container
  become: true
  ansible.posix.firewalld:
    port: 2221/tcp
    permanent: true
    state: enabled
    immediate: true

- name: Allow SSH Ubuntu container 
  become: true
  ansible.posix.firewalld:
    port: 2222/tcp
    permanent: true
    state: enabled
    immediate: true
