- name: Pull the registry image with Docker
  community.docker.docker_image:
    name: docker.io/library/registry:2
    source: pull

- name: Run a Registry container with Docker
  community.docker.docker_container: 
    name: "{{ registry_name_docker }}"
    image: docker.io/library/registry:2
    state: started
    published_ports: 
      - "{{ registry_port_docker }}:{{ registry_container_port }}"
    volumes:
      - "{{ registry_volume_name }}:/var/lib/registry"

- name: Allow Registry port (Docker)
  become: true
  ansible.posix.firewalld:
    port: "{{ registry_port_docker }}/tcp"
    permanent: true
    state: enabled
    immediate: true