---
- name: Pull the registry image with Podman
  containers.podman.podman_image:
    name: docker.io/library/registry:2
    state: present
  when: podman_installed

- name: Pull the registry image with Docker
  community.docker.docker_image:
    name: docker.io/library/registry:2
    source: pull
  when: docker_installed

- name: Run a Registry container with Podman
  containers.podman.podman_container:
    name: registry_p
    image: docker.io/library/registry:2
    state: started
    publish: "5001:5000"
  when: podman_installed

- name: Run a Registry container with Docker
  community.docker.docker_container: 
    name: registry_d
    image: docker.io/library/registry:2
    state: started
    published_ports: 
      - "5002:5000"
  when: docker_installed

- name: Allow Registry port (Podman)
  become: true 
  ansible.posix.firewalld:
   port: 5001/tcp
   permanent: true
   state: enabled
   immediate: true

- name: Allow Registry port (Docker)
  become: true
  ansible.posix.firewalld:
    port: 5002/tcp
    permanent: true
    state: enabled
    immediate: true
