---
- name: Check if Docker is installed
  ansible.builtin.command: docker --version
  register: docker_check
  changed_when: false
  failed_when: false

- name: Check if Podman is installed
  ansible.builtin.command: podman --version
  register: podman_check
  changed_when: false
  failed_when: false

- name: Set docker_installed fact
  ansible.builtin.set_fact:
    docker_installed: "{{ docker_check.rc == 0 }}"

- name: Set podman_installed fact
  ansible.builtin.set_fact: 
    podman_installed: "{{ podman_check.rc == 0 }}" 
