---
- name: Copy Rocky Containerfile
  ansible.builtin.copy:
    src: rocky/Containerfile
    dest: /tmp/Containerfile-rocky

- name: Copy Ubuntu Containerfile
  ansible.builtin.copy:
    src: ubuntu/Containerfile
    dest: /tmp/Containerfile-ubuntu

- name: Copy SSH public key
  ansible.builtin.copy:
    remote_src: true
    src: /home/vagrant/.ssh/id-genericuser.pub
    dest: /tmp/id-key-genericuser.pub

- name: Build Rocky image
  containers.podman.podman_image:
    name: rocky-ssh
    path: /tmp
    build:
      file: /tmp/Containerfile-rocky

- name: Build Ubuntu image
  containers.podman.podman_image:
    name: ubuntu-ssh
    path: /tmp
    build:
      file: /tmp/Containerfile-ubuntu

- name: Create container network
  containers.podman.podman_network:
    name: container_network
    state: present

- name: Run Rocky container
  containers.podman.podman_container:
    name: rocky-ssh
    image: rocky-ssh
    state: started
    restart_policy: always
    network:
      - container_network
    publish:
      - "2221:22"

- name: Run Ubuntu container
  containers.podman.podman_container:
    name: ubuntu-ssh
    image: ubuntu-ssh
    state: started
    restart_policy: always
    network: container_network
    publish:
      - "2222:22"
