---
- name: Copy Rocky Containerfile
  ansible.builtin.copy:
    src: Containerfile-rocky
    dest: /tmp/Containerfile-rocky

- name: Copy Ubuntu Containerfile
  ansible.builtin.copy:
    src: Containerfile-ubuntu
    dest: /tmp/Containerfile-ubuntu

- name: Copy SSH public key
  ansible.builtin.copy:
    remote_src: true
    src: /home/vagrant/.ssh/id-genericuser.pub
    dest: /tmp/id-key-genericuser.pub

- name: Build Rocky image
  containers.podman.podman_image:
    name: "{{ rocky_container_name }}"
    path: /tmp
    build:
      file: /tmp/Containerfile-rocky

- name: Build Ubuntu image
  containers.podman.podman_image:
    name: "{{ ubuntu_container_name }}"
    path: /tmp
    build:
      file: /tmp/Containerfile-ubuntu

- name: Create container network
  containers.podman.podman_network:
    name: "{{ container_network_name }}"
    state: present

- name: Run Rocky container
  containers.podman.podman_container:
    name: "{{ rocky_container_name }}"
    image: "{{ rocky_container_name }}"
    state: started
    restart_policy: always
    network:
      - "{{ container_network_name }}"
    publish:
      - "{{ rocky_host_ssh_port }}:22"

- name: Run Ubuntu container
  containers.podman.podman_container:
    name: "{{ ubuntu_container_name }}"
    image: "{{ ubuntu_container_name }}"
    state: started
    restart_policy: always
    network: "{{ container_network_name }}"
    publish:
      - "{{ ubuntu_host_ssh_port }}:22"
