---
- name: Allow SSH Rocky container
  become: true
  ansible.posix.firewalld:
    port: "{{ rocky_host_ssh_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true

- name: Allow SSH Ubuntu container 
  become: true
  ansible.posix.firewalld:
    port: "{{ ubuntu_host_ssh_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
