---
- name: Pull the registry image
  containers.podman.podman_image:
    name: docker.io/library/registry:2
    state: present

- name: Run a Registry container
  containers.podman.podman_container:
    name: registry
    image: docker.io/library/registry:2
    publish: "{{ registry_host_port }}:{{ registry_container_port }}"
    volume:
      - "{{ registry_volume_name }}:/var/lib/registry"

- name: Allow Registry port
  become: true
  ansible.posix.firewalld:
    port: "{{ registry_host_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
